# Generated by Django 5.2.3 on 2025-06-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
                ('terrains', models.CharField(max_length=200)),
                ('climates', models.CharField(max_length=200)),
            ],
        ),
    ]
