# Generated by Django 5.2.3 on 2025-06-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets_connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climates',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrains',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
